dominic:
  timezone: US/Pacific
  include:
    - event
    - raid-hour
    - pokemon-spotlight-hour
    - community-day
    - raid-day
    - ticketed-event
    - pokemon-go-tour
    - research
    - wild-area
    - research-day
    - max-mondays
