AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pokémon GO Calendar powered by Leek Duck (leekduck.com) and ScrapedDuck.

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  ICalFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /ical
            Method: GET
      Environment:
        Variables:
          PARAM1: VALUE
    Metadata:
      DockerTag: provided.al2-v1
      DockerContext: ./ical
      Dockerfile: Dockerfile