name: generate

on:
  push:
    branches:
      - github-actions

jobs:
  ical:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # changed files back to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Run generator
        run: go run ./cmd/generate

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: ./data/*